/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.kennysspot.ui;

import java.io.*;
import javax.swing.*;

/**
 *
 * @author Kenny
 */
public class FilesUI extends javax.swing.JFrame{

	/** Creates new form FilesUI */
	public FilesUI(){
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          fileChooser = new javax.swing.JFileChooser();
          jScrollPane1 = new javax.swing.JScrollPane();
          textArea = new javax.swing.JTextArea();
          jMenuBar1 = new javax.swing.JMenuBar();
          menuFile = new javax.swing.JMenu();
          Open = new javax.swing.JMenuItem();
          menuExit = new javax.swing.JMenu();
          menuExitApp = new javax.swing.JMenuItem();

          fileChooser.setDialogTitle("This is my open dialog");

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          textArea.setColumns(20);
          textArea.setRows(5);
          jScrollPane1.setViewportView(textArea);

          menuFile.setText("File");

          Open.setText("Open");
          Open.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    OpenActionPerformed(evt);
               }
          });
          menuFile.add(Open);

          jMenuBar1.add(menuFile);

          menuExit.setText("Exit");
          menuExit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuExitActionPerformed(evt);
               }
          });

          menuExitApp.setText("Exit Application");
          menuExitApp.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuExitAppActionPerformed(evt);
               }
          });
          menuExit.add(menuExitApp);

          jMenuBar1.add(menuExit);

          setJMenuBar(jMenuBar1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addContainerGap())
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
		// TODO add your handling code here:
     }//GEN-LAST:event_menuExitActionPerformed

     private void menuExitAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitAppActionPerformed
		System.exit(0);
     }//GEN-LAST:event_menuExitAppActionPerformed

     private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
		int returnVal = fileChooser.showOpenDialog(this);
		if(returnVal == JFileChooser.APPROVE_OPTION){
			File file = fileChooser.getSelectedFile();
			try{
				textArea.read(new FileReader(file.getAbsolutePath()), null);
			}catch(IOException ex){
				System.out.println("File access cancelled by user.");
			}
		}
     }//GEN-LAST:event_OpenActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]){
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
				if("Nimbus".equals(info.getName())){
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}catch(ClassNotFoundException ex){
			java.util.logging.Logger.getLogger(FilesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(InstantiationException ex){
			java.util.logging.Logger.getLogger(FilesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(IllegalAccessException ex){
			java.util.logging.Logger.getLogger(FilesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(javax.swing.UnsupportedLookAndFeelException ex){
			java.util.logging.Logger.getLogger(FilesUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new FilesUI().setVisible(true);
		});
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JMenuItem Open;
     private javax.swing.JFileChooser fileChooser;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JMenu menuExit;
     private javax.swing.JMenuItem menuExitApp;
     private javax.swing.JMenu menuFile;
     private javax.swing.JTextArea textArea;
     // End of variables declaration//GEN-END:variables
}
