/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package binaryreader;

/**
 *
 * @author Kenny Coltharp
 */
public class conversionFrame extends javax.swing.JFrame{

	/** Creates new form conversionFrame */
	public conversionFrame(){
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          topPanel = new javax.swing.JPanel();
          inputTextField = new javax.swing.JTextField();
          decimalOutTextField = new javax.swing.JTextField();
          binayOutTextField = new javax.swing.JTextField();
          hexOutTextField = new javax.swing.JTextField();
          octalOutTextField = new javax.swing.JTextField();
          jLabel1 = new javax.swing.JLabel();
          jLabel2 = new javax.swing.JLabel();
          jLabel3 = new javax.swing.JLabel();
          jLabel4 = new javax.swing.JLabel();
          jLabel5 = new javax.swing.JLabel();
          convertButton = new javax.swing.JButton();
          resetButtom = new javax.swing.JButton();
          exitButton = new javax.swing.JButton();
          jMenuBar1 = new javax.swing.JMenuBar();
          fileMenu = new javax.swing.JMenu();
          exitMenu = new javax.swing.JMenu();
          exitItem = new javax.swing.JMenuItem();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Number Conversion");
          setAlwaysOnTop(true);

          topPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

          inputTextField.setText("Input Number");

          decimalOutTextField.setText("Decimal Number");
          decimalOutTextField.setEnabled(false);
          decimalOutTextField.setMargin(new java.awt.Insets(2, 5, 2, 5));

          binayOutTextField.setText("Binay Number");
          binayOutTextField.setEnabled(false);
          binayOutTextField.setMargin(new java.awt.Insets(2, 5, 2, 5));

          hexOutTextField.setText("Hex Number");
          hexOutTextField.setEnabled(false);
          hexOutTextField.setMargin(new java.awt.Insets(2, 5, 2, 5));

          octalOutTextField.setText("Octal Number");
          octalOutTextField.setEnabled(false);
          octalOutTextField.setMargin(new java.awt.Insets(2, 5, 2, 5));

          jLabel1.setText("Converted Decimal");

          jLabel2.setText("Converted Hex");

          jLabel3.setText("Converted Binary");

          jLabel4.setText("Input number to convert:");

          jLabel5.setText("Converted Octal");

          javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
          topPanel.setLayout(topPanelLayout);
          topPanelLayout.setHorizontalGroup(
               topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(octalOutTextField)
                         .addComponent(binayOutTextField, javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(topPanelLayout.createSequentialGroup()
                                   .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(decimalOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel4))
                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                   .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(hexOutTextField)
                                        .addGroup(topPanelLayout.createSequentialGroup()
                                             .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(jLabel2)
                                                  .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                             .addGap(0, 0, Short.MAX_VALUE))))
                              .addComponent(jLabel3)
                              .addComponent(jLabel5)))
                    .addContainerGap())
          );
          topPanelLayout.setVerticalGroup(
               topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(topPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(jLabel4))
                    .addGap(23, 23, 23)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(decimalOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(hexOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(binayOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(octalOutTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          convertButton.setText("Convert");
          convertButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    convertButtonActionPerformed(evt);
               }
          });

          resetButtom.setText("Reset Form");
          resetButtom.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    resetButtomActionPerformed(evt);
               }
          });

          exitButton.setText("Exit");
          exitButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitButtonActionPerformed(evt);
               }
          });

          fileMenu.setText("File");
          jMenuBar1.add(fileMenu);

          exitMenu.setText("Exit");

          exitItem.setText("Exit Application");
          exitItem.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    exitItemActionPerformed(evt);
               }
          });
          exitMenu.add(exitItem);

          jMenuBar1.add(exitMenu);

          setJMenuBar(jMenuBar1);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(layout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                              .addGap(10, 10, 10)
                              .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                              .addContainerGap()
                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(resetButtom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                   .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(convertButton)
                    .addGap(18, 18, 18)
                    .addComponent(resetButtom)
                    .addGap(18, 18, 18)
                    .addComponent(exitButton)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void exitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitItemActionPerformed

		System.exit(0);
     }//GEN-LAST:event_exitItemActionPerformed

     private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed

		System.exit(0);
     }//GEN-LAST:event_exitButtonActionPerformed

     private void resetButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtomActionPerformed
		binayOutTextField.setText("");
		hexOutTextField.setText("");
		decimalOutTextField.setText("");
		octalOutTextField.setText("");
		inputTextField.setText("Input number to convert.");
     }//GEN-LAST:event_resetButtomActionPerformed

     private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
		int inputNum, binaryNum, decimalNum, hexNum, octalNum;
		String inputString, binaryString, decimalString, hexString, octalString;

		inputString = inputTextField.getText();
		inputNum = Integer.parseInt(inputString);

		binaryString = Integer.toBinaryString(inputNum);
		binayOutTextField.setText(binaryString);

		hexString = Integer.toHexString(inputNum);
		hexOutTextField.setText(hexString);

		decimalString = Integer.toString(inputNum);
		decimalOutTextField.setText(decimalString);

		octalString = Integer.toOctalString(inputNum);
		octalOutTextField.setText(octalString);

     }//GEN-LAST:event_convertButtonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]){
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try{
			for(javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()){
				if("Nimbus".equals(info.getName())){
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		}catch(ClassNotFoundException ex){
			java.util.logging.Logger.getLogger(conversionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(InstantiationException ex){
			java.util.logging.Logger.getLogger(conversionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(IllegalAccessException ex){
			java.util.logging.Logger.getLogger(conversionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}catch(javax.swing.UnsupportedLookAndFeelException ex){
			java.util.logging.Logger.getLogger(conversionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable(){
			public void run(){
				new conversionFrame().setVisible(true);
			}
		});
	}

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTextField binayOutTextField;
     private javax.swing.JButton convertButton;
     private javax.swing.JTextField decimalOutTextField;
     private javax.swing.JButton exitButton;
     private javax.swing.JMenuItem exitItem;
     private javax.swing.JMenu exitMenu;
     private javax.swing.JMenu fileMenu;
     private javax.swing.JTextField hexOutTextField;
     private javax.swing.JTextField inputTextField;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JLabel jLabel5;
     private javax.swing.JMenuBar jMenuBar1;
     private javax.swing.JTextField octalOutTextField;
     private javax.swing.JButton resetButtom;
     private javax.swing.JPanel topPanel;
     // End of variables declaration//GEN-END:variables
}
